### ISSUE TITLE
VideoJS player src is empty

### ISSUE THREAD

**Issue by gjost** [denshoproject/ddr-public#169]
Issues with some audio/visual entities on ddrstage
- https://ddrstage.densho.org/ddr-csujad-38-602/
- ddr-csujad-38 entities 583 thru 602
- https://ddrstage.densho.org/ddr-csujad-51-1/

Video metadata is present but no video is selected by the template and `<source src`  is empty.  Download links are also empty.
```
    <!--
    templatekey: av:video
    template:    ui/entities/detail-video.html
    IA metadata: {'id': 'ddr-csujad-51-1', 'original': 'ddr-csujad-51-1-mezzanine-b7b00d2a3f.mp4', 'mimetype': 'video/mp4', 'files': {'mp3': {'name': 'ddr-csujad-51-1-mezzanine-b7b00d2a3f.mp3', 'source': 'derivative', 'bitrate': '96', 'format': 'mp3', 'original': 'ddr-csujad-51-1-mezzanine-b7b00d2a3f.mp4', 'mtime': '1619468189', 'size': '75376315', 'md5': 'd3e79552412c58497a7c40e781587292', 'crc32': '7a2e71da', 'sha1': '8bd6505c7107c52b298f561fe7dcaa4d63101f68', 'length': '6274.97', 'height': '0', 'width': '0', 'mimetype': 'audio/mpeg', 'url': 'https://archive.org/download/ddr-csujad-51-1/ddr-csujad-51-1-mezzanine-b7b00d2a3f.mp3'}, 'mpg': {'name': 'ddr-csujad-51-1-mezzanine-b7b00d2a3f.mp4', 'source': 'original', 'mtime': '1619459825', 'size': '1727571482', 'md5': 'fe06d70986e182b65400647573bacca5', 'crc32': '82a4c7ba', 'sha1': 'b7b00d2a3f32d3c8c1ce81a8d9686a9bd37b3b3b', 'format': 'mpg', 'length': '6274.98', 'height': '1080', 'width': '1920', 'mimetype': 'video/mp4', 'url': 'https://archive.org/download/ddr-csujad-51-1/ddr-csujad-51-1-mezzanine-b7b00d2a3f.mp4'}}}
    -->
    <!-- begin VideoJS player -->
    <video id="clip" class="embed-responsive embed-responsive-16by9 video-js vjs-big-play-centered vjs-fluid" controls preload="auto" width="560" height="384" poster="" data-setup="{}">
>>>   <source src="" type="video/mp4">
      <p class="vjs-no-js">
        To view this video please enable JavaScript, and consider upgrading to a web browser that
        <a href="http://videojs.com/html5-video-support/" target="_blank">supports HTML5 video</a>
      </p>
    </video>
    <!-- end VideoJS player-->
```

**Comment by gjost** [comment]
The code did not correctly handle actual "MPEG4" files which is what the ddr-public template code is actually looking for.  Fixed in ddr-cmdln `develop` branch commit `c0ff16b`.

**Comment by gjost** [comment]
Not done yet: issue with ddr-csujad-29-396:
```
    Traceback (most recent call last):
      File "/opt/ddr-cmdln/venv/cmdln/bin/ddrindex", line 33, in <module>
        sys.exit(load_entry_point('ddr-cmdln==5.0.17', 'console_scripts', 'ddrindex')())
      File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.0.17-py3.7.egg/DDR/cli/ddrindex.py", line 335, in publish
        path, recursive=recurse, force=force, backblaze=backblaze
      File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.0.17-py3.7.egg/DDR/docstore.py", line 695, in post_multi
        document, parents=parents, b2=b2_synced, force=True
      File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.0.17-py3.7.egg/DDR/docstore.py", line 577, in post
        public_fields=public_fields, public=public, b2=b2
      File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.0.17-py3.7.egg/DDR/models/common.py", line 420, in to_esobject
        d.ia_meta = archivedotorg.get_ia_meta(self)
      File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.0.17-py3.7.egg/DDR/archivedotorg.py", line 25, in get_ia_meta
        data = process_ia_metadata(o.identifier.id, iaobject['files'])
    KeyError: 'files'
```

**Comment by gjost** [comment]
ddr-csujad-29-396 looks fine on this end.

Found a different error with https://archive.org/details/ddr-csujad-29-72: Internet Archive reports "unable to load metadata from item location"
https://archive.org/details/ddr-csujad-29-72

Also this traceback for ddr-csujad-29-1:
```
Traceback (most recent call last):
  File "/opt/ddr-cmdln/venv/cmdln/bin/ddrindex", line 33, in <module>
    sys.exit(load_entry_point('ddr-cmdln==5.0.17', 'console_scripts', 'ddrindex')())
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.0.17-py3.7.egg/DDR/cli/ddrindex.py", line 335, in publish
    path, recursive=recurse, force=force, backblaze=backblaze
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.0.17-py3.7.egg/DDR/docstore.py", line 695, in post_multi
    document, parents=parents, b2=b2_synced, force=True
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.0.17-py3.7.egg/DDR/docstore.py", line 577, in post
    public_fields=public_fields, public=public, b2=b2
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.0.17-py3.7.egg/DDR/models/common.py", line 422, in to_esobject
    d.template = archivedotorg.format_mimetype(self, d.ia_meta)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.0.17-py3.7.egg/DDR/archivedotorg.py", line 143, in format_mimetype
    meta['mimetype'].split('/')[0]
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by GeoffFroh** [comment]
Related to indexer issue in https://github.com/denshoproject/issues/199
