### ISSUE TITLE
No mimetype for segment

### ISSUE THREAD

**Issue by gjost** [denshoproject/ddr-public#171]
`ddrindex` crashes when trying to index `ddr-densho-1021-1-1`:
```
(cmdln) ddr@denshodeb10:/opt/ddr-cmdln$ ddrindex publish -r /var/www/media/ddr/ddr-densho-1021/files/ddr-densho-1021-1
2021-05-18 16:34:03.057645-07:00 | 1/74 POST ddr-densho-1021-1-transcript-7132f32ac0            
...
2021-05-18 16:34:09.554647-07:00 | 69/74 POST ddr-densho-1021-1-1 
Traceback (most recent call last):
  File "/opt/ddr-cmdln/venv/cmdln/bin/ddrindex", line 33, in <module>
    sys.exit(load_entry_point('ddr-cmdln==5.2.2', 'console_scripts', 'ddrindex')())
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.2.2-py3.7.egg/DDR/cli/ddrindex.py", line 335, in publish
    path, recursive=recurse, force=force, backblaze=backblaze
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.2.2-py3.7.egg/DDR/docstore.py", line 695, in post_multi
    document, parents=parents, b2=b2_synced, force=True
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.2.2-py3.7.egg/DDR/docstore.py", line 577, in post
    public_fields=public_fields, public=public, b2=b2
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.2.2-py3.7.egg/DDR/models/common.py", line 420, in to_esobject
    d.ia_meta = archivedotorg.get_ia_meta(self)
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.2.2-py3.7.egg/DDR/archivedotorg.py", line 27, in get_ia_meta
    data = process_ia_metadata(o.identifier.id, iaobject['files'])
  File "/opt/ddr-cmdln/venv/cmdln/lib/python3.7/site-packages/ddr_cmdln-5.2.2-py3.7.egg/DDR/archivedotorg.py", line 129, in process_ia_metadata
    if file_mimetype.split('/')[0] == orig_mimetype.split('/')[0]:
AttributeError: 'NoneType' object has no attribute 'split'
```

**Comment by gjost** [comment]
This is really a ddr-cmdln issue: https://github.com/denshoproject/ddr-cmdln/issues/202
