### ISSUE TITLE
Crash when transcript File set as Entity signature

### ISSUE THREAD

**Issue by gjost** [denshoproject/ddr-public#178]
Some Entities have transcripts as their signature Files. The view throws a 500 because it can't find an image.  Example: https://ddr.densho.org/ddr-densho-142-213/
```
Environment:
Request Method: GET
Request URL: http://ddr.densho.org/ddr-densho-142-213/

Django Version: 3.1.7
Python Version: 3.7.3
Installed Applications:
('django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.sites',
 'django.contrib.sitemaps',
 'django.contrib.staticfiles',
 'bootstrap_pagination',
 'corsheaders',
 'drf_yasg',
 'rest_framework',
 'robots',
 'sorl.thumbnail',
 'ddrpublic',
 'ui',
 'names')
Installed Middleware:
['django.middleware.security.SecurityMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware']

Traceback (most recent call last):
  File "/opt/ddr-public/venv/ddrpublic/lib/python3.7/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/opt/ddr-public/venv/ddrpublic/lib/python3.7/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/ddr-public/ddrpublic/ui/views/objects.py", line 29, in detail
    elif o['model'] == 'entity': return entities.detail(request, oid)
  File "/opt/ddr-public/ddrpublic/ui/views/entities.py", line 59, in detail
    signature['access_size'] = models.file_size(signature['links']['img'])

Exception Type: KeyError at /ddr-densho-142-213/
Exception Value: 'img'
```

**Comment by GeoffFroh** [comment]
This may be an issue that needs to be addressed in the `ddr-cmdln` indexer. Perhaps that code can use a generic image icon if the signature file does not have an access file (i.e., is a format like .html that does not support thumbnailing)

**Comment by gjost** [comment]
I have a quick fix in place to prevent the view from throwing a 500.  I'll try adding that logic to the `ddr-cmdln` indexer.

**Comment by gjost** [comment]
For reference, there are several ways for users to (re)set signatures.

1. In the REPL, load an object and set `OBJECT.signature_id`.
2. In the web UI, go to a File detail page and select "Make collection/object signature".
3. Use `ddrsignatures` to automatically choose signatures for an entire collection.
4. in the web UI, `/ui/collection/COLLECTION-ID/signatures/` (no link/button).

#1 and #2 simply update `OBJECT.signature_id`.  #3 and #4 run some version of the following code:
```
    updates = signatures.find_updates(
        signatures.choose(
            util.find_meta_files(collection.path, recursive=True, force_read=True)
        )
    )
```

**Comment by gjost** [comment]
Fixed in `ddrpublic` `master` branch hotfix commit `c7f57c2`,
